Test
jupyter-xeus/xeus-calc pull request #10
Opened 2019-07-05 13:33 UTC by ThibaultLacharme

2019-07-05 13:35 UTC, martinRenou requested changes

2019-07-05 13:35 UTC, martinRenou commented on src/test_calculator.hpp
> +#ifndef TEST_CALCULATOR_HPP
I guess you did not mean to commit this file, it is in `src/`

2019-07-08 14:20 UTC, JohanMabille requested changes

2019-07-08 14:20 UTC, JohanMabille commented on CMakeLists.txt
> +#    )
Please do not commit commented code

2019-07-08 14:20 UTC, JohanMabille commented on CMakeLists.txt
>  # My kernel executable
This comment is now irrelevant

2019-07-08 14:20 UTC, JohanMabille commented on src/xeus_calc_interpreter.cpp
> +            char c = token[0]; // study the first character of the token at each loop
study => checks

2019-07-08 14:20 UTC, JohanMabille commented on test/CMakeLists.txt
> +#include(CheckCXXCompilerFlag)
to be removed

2019-07-08 14:20 UTC, JohanMabille commented on test/CMakeLists.txt
> +#include(set_compiler_flag.cmake)
same remark

2019-07-08 14:20 UTC, JohanMabille commented on src/xeus_calc_interpreter.cpp
> +                if (evaluation.size() >= 2) // error management, checks for missing operand
Comment not really meaningful

2019-07-08 14:20 UTC, JohanMabille commented on src/xeus_calc_interpreter.cpp
> +                parsed_infix << token << ' '; // if the first value of the token is the number, we can assume that the whole token is composed of numbers and thus push it
Comments should be placed before the code

2019-07-08 14:34 UTC, JohanMabille approved these changes

2019-07-08 14:34 UTC, merged